### ISSUE TITLE
Create Plant Profile Page

### ISSUE THREAD

**Issue by paniolonate** [LetUmGrow/LetUmGrow#67]
- link Plant ID pages to list-plants page

- add drop down of plants in the edit form

- add functionality

- enable type of plant to be assigned to specific plot

**Comment by matthew-schultz** [comment]
- outline what to display on the plant profile page
  - name
  - picture
  - map with location
  - status feed
- create fields in the Plants schema for those sections/modules
- implement everything on plants/profile/_id page
- test and obtain feedback from users (students, landscaping dept, etc)
