### ISSUE TITLE
User profile functionality

### ISSUE THREAD

**Issue by billmullen42** [LetUmGrow/LetUmGrow#85]
- Pull in username and UserId from CAS
- Server identifies user, and creates default profile whenever profile page is loaded (if user is not already in user collection)
- Create edit profile page
- Add profile details to user page
- Add picture via link

**Comment by matthew-schultz** [comment]
For further reference:
https://guide.meteor.com/accounts.html
https://themeteorchef.com/recipes/building-a-user-admin/
